//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolderWatcherDiagnostic.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\HNBGI\\QUEUED_SCN_DOCS\\")]
        public string QueuedDocsPath {
            get {
                return ((string)(this["QueuedDocsPath"]));
            }
            set {
                this["QueuedDocsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RENEWAL_ADDED")]
        public string RenewalAddedStatus {
            get {
                return ((string)(this["RenewalAddedStatus"]));
            }
            set {
                this["RenewalAddedStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CANCELLATION_ADDED")]
        public string CancellationAddedStatus {
            get {
                return ((string)(this["CancellationAddedStatus"]));
            }
            set {
                this["CancellationAddedStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ENDORSEMENT_ADDED")]
        public string EndorsementAddedStatus {
            get {
                return ((string)(this["EndorsementAddedStatus"]));
            }
            set {
                this["EndorsementAddedStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\HNBGI\\SCN_DOCS_3\\")]
        public string SavedDocsPath {
            get {
                return ((string)(this["SavedDocsPath"]));
            }
            set {
                this["SavedDocsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\HNBGI\\UNKNOWN_SCN_DOCS\\")]
        public string UnknownDocsPath {
            get {
                return ((string)(this["UnknownDocsPath"]));
            }
            set {
                this["UnknownDocsPath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(" SERVER=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST= 192.168.10.160)(PORT=1580))(CO" +
            "NNECT_DATA=(SERVICE_NAME=APPS))); uid=hnba_crc;pwd=HNBACRC;")]
        public string connectionString {
            get {
                return ((string)(this["connectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OK")]
        public string NewStatus {
            get {
                return ((string)(this["NewStatus"]));
            }
            set {
                this["NewStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INITIAL")]
        public string NewFastTrackAddedStatus {
            get {
                return ((string)(this["NewFastTrackAddedStatus"]));
            }
            set {
                this["NewFastTrackAddedStatus"] = value;
            }
        }
    }
}
